export const jobs = [
  {
    jobId: "49790139",
    jobTitle: "Corporate Integration Executive",
    jobCompany: "HDFC Bank",
    jobSector: "Finance",
    jobDomain: "Corporate Finance",
    jobLevel: "Senior",
    jobDescription:
      "Responsible for overseeing corporate integration projects and ensuring seamless processes across departments.",
    jobSalary: 15, // in LPA
    skillsRequired: [
      "Project Management",
      "Corporate Strategy",
      "Financial Analysis",
    ],
    jobLocation: "Mumbai",
    jobVacancies: 5,
    jobVacanciesRemaining: 2,
    jobApplicants: ["JOBSN202308060001", "JOBSN202308060002"],
  },
  {
    jobId: "63958436",
    jobTitle: "Global Implementation Architect",
    jobCompany: "Infosys",
    jobSector: "IT",
    jobDomain: "Software Implementation",
    jobLevel: "Mid",
    jobDescription:
      "Leads global software implementation projects, ensuring adherence to accountability standards and timelines.",
    jobSalary: 18, // in LPA
    skillsRequired: [
      "Software Architecture",
      "Global Implementation",
      "Stakeholder Management",
    ],
    jobLocation: "Bengaluru",
    jobVacancies: 3,
    jobVacanciesRemaining: 1,
    jobApplicants: ["JOBSN202308060003"],
  },
  {
    jobId: "85430218",
    jobTitle: "Senior Software Engineer",
    jobCompany: "Tata Consultancy Services",
    jobSector: "Technology",
    jobDomain: "Software Development",
    jobLevel: "Senior",
    jobDescription:
      "Develop and maintain software applications, ensuring high performance and scalability.",
    jobSalary: 20, // in LPA
    skillsRequired: ["JavaScript", "React", "Node.js"],
    jobLocation: "Pune",
    jobVacancies: 4,
    jobVacanciesRemaining: 3,
    jobApplicants: ["JOBSN202308060004", "JOBSN202308060005"],
  },
  {
    jobId: "22948320",
    jobTitle: "Healthcare Data Analyst",
    jobCompany: "Apollo Hospitals",
    jobSector: "Healthcare",
    jobDomain: "Data Analysis",
    jobLevel: "Mid",
    jobDescription:
      "Analyze healthcare data to provide actionable insights and improve patient outcomes.",
    jobSalary: 12, // in LPA
    skillsRequired: ["Data Analysis", "SQL", "Healthcare Analytics"],
    jobLocation: "Chennai",
    jobVacancies: 2,
    jobVacanciesRemaining: 2,
    jobApplicants: [],
  },
  {
    jobId: "94830217",
    jobTitle: "Financial Advisor",
    jobCompany: "Bajaj Finance",
    jobSector: "Finance",
    jobDomain: "Financial Planning",
    jobLevel: "Junior",
    jobDescription:
      "Provide financial advice and planning services to clients, helping them achieve their financial goals.",
    jobSalary: 10, // in LPA
    skillsRequired: [
      "Financial Planning",
      "Client Management",
      "Investment Strategies",
    ],
    jobLocation: "Delhi",
    jobVacancies: 3,
    jobVacanciesRemaining: 1,
    jobApplicants: ["JOBSN202308060006", "JOBSN202308060007"],
  },
  {
    jobId: "57382910",
    jobTitle: "IT Support Specialist",
    jobCompany: "Wipro",
    jobSector: "IT",
    jobDomain: "Technical Support",
    jobLevel: "Entry",
    jobDescription:
      "Provide technical support and troubleshooting services for IT systems and applications.",
    jobSalary: 8, // in LPA
    skillsRequired: [
      "Technical Support",
      "Troubleshooting",
      "Customer Service",
    ],
    jobLocation: "Hyderabad",
    jobVacancies: 5,
    jobVacanciesRemaining: 4,
    jobApplicants: ["JOBSN202308060008"],
  },
  {
    jobId: "28493716",
    jobTitle: "Marketing Manager",
    jobCompany: "Unacademy",
    jobSector: "Education",
    jobDomain: "Digital Marketing",
    jobLevel: "Mid",
    jobDescription:
      "Develop and implement marketing strategies to promote educational products and services.",
    jobSalary: 14, // in LPA
    skillsRequired: ["Digital Marketing", "Campaign Management", "SEO/SEM"],
    jobLocation: "Bengaluru",
    jobVacancies: 4,
    jobVacanciesRemaining: 3,
    jobApplicants: ["JOBSN202308060001", "JOBSN202308060003"],
  },
  {
    jobId: "39485721",
    jobTitle: "Product Manager",
    jobCompany: "Byju's",
    jobSector: "Education",
    jobDomain: "Product Management",
    jobLevel: "Senior",
    jobDescription:
      "Lead product development efforts, ensuring alignment with business goals and customer needs.",
    jobSalary: 22, // in LPA
    skillsRequired: [
      "Product Management",
      "Agile Methodologies",
      "User Experience",
    ],
    jobLocation: "Bengaluru",
    jobVacancies: 2,
    jobVacanciesRemaining: 1,
    jobApplicants: ["JOBSN202308060002", "JOBSN202308060004"],
  },
  {
    jobId: "48592031",
    jobTitle: "Chief Marketing Officer",
    jobCompany: "Reliance Industries",
    jobSector: "Retail",
    jobDomain: "Marketing Strategy",
    jobLevel: "Executive",
    jobDescription:
      "Oversee the development and execution of marketing strategies to drive business growth.",
    jobSalary: 35, // in LPA
    skillsRequired: ["Marketing Strategy", "Leadership", "Brand Management"],
    jobLocation: "Mumbai",
    jobVacancies: 1,
    jobVacanciesRemaining: 0,
    jobApplicants: ["JOBSN202308060006", "JOBSN202308060008"],
  },
  {
    jobId: "57382145",
    jobTitle: "Network Security Engineer",
    jobCompany: "Tata Communications",
    jobSector: "Telecommunications",
    jobDomain: "Network Security",
    jobLevel: "Mid",
    jobDescription:
      "Implement and manage network security measures to protect the organization's IT infrastructure.",
    jobSalary: 16, // in LPA
    skillsRequired: [
      "Network Security",
      "Firewall Management",
      "Incident Response",
    ],
    jobLocation: "Chennai",
    jobVacancies: 3,
    jobVacanciesRemaining: 3,
    jobApplicants: [],
  },
  {
    jobId: "84736290",
    jobTitle: "Operations Manager",
    jobCompany: "Flipkart",
    jobSector: "E-commerce",
    jobDomain: "Operations Management",
    jobLevel: "Senior",
    jobDescription:
      "Oversee and optimize operational processes to ensure efficiency and effectiveness.",
    jobSalary: 25, // in LPA
    skillsRequired: [
      "Operations Management",
      "Process Improvement",
      "Team Leadership",
    ],
    jobLocation: "Bengaluru",
    jobVacancies: 2,
    jobVacanciesRemaining: 1,
    jobApplicants: ["JOBSN202308060004", "JOBSN202308060007"],
  },
  {
    jobId: "92735481",
    jobTitle: "UX/UI Designer",
    jobCompany: "Ola",
    jobSector: "Transport",
    jobDomain: "UX/UI Design",
    jobLevel: "Mid",
    jobDescription:
      "Design user interfaces and experiences for the company's digital products.",
    jobSalary: 15, // in LPA
    skillsRequired: ["UX Design", "UI Design", "Prototyping"],
    jobLocation: "Bengaluru",
    jobVacancies: 3,
    jobVacanciesRemaining: 2,
    jobApplicants: ["JOBSN202308060003", "JOBSN202308060008"],
  },
  {
    jobId: "36478215",
    jobTitle: "Business Development Executive",
    jobCompany: "Paytm",
    jobSector: "Fintech",
    jobDomain: "Business Development",
    jobLevel: "Junior",
    jobDescription:
      "Identify and pursue new business opportunities to drive company growth.",
    jobSalary: 12, // in LPA
    skillsRequired: [
      "Business Development",
      "Sales Strategy",
      "Client Relations",
    ],
    jobLocation: "Noida",
    jobVacancies: 4,
    jobVacanciesRemaining: 2,
    jobApplicants: ["JOBSN202308060002", "JOBSN202308060008"],
  },
  {
    jobId: "48293761",
    jobTitle: "Data Scientist",
    jobCompany: "Zomato",
    jobSector: "Foodtech",
    jobDomain: "Data Analysis",
    jobLevel: "Mid",
    jobDescription:
      "Analyze and interpret complex data to provide actionable insights for business decision-making.",
    jobSalary: 18, // in LPA
    skillsRequired: ["Data Analysis", "Machine Learning", "Python"],
    jobLocation: "Gurgaon",
    jobVacancies: 2,
    jobVacanciesRemaining: 1,
    jobApplicants: ["JOBSN202308060001"],
  },
  {
    jobId: "57384921",
    jobTitle: "Content Writer",
    jobCompany: "Swiggy",
    jobSector: "Foodtech",
    jobDomain: "Content Creation",
    jobLevel: "Entry",
    jobDescription:
      "Create engaging and informative content for the company's digital platforms.",
    jobSalary: 9, // in LPA
    skillsRequired: ["Content Writing", "SEO", "Creativity"],
    jobLocation: "Bengaluru",
    jobVacancies: 5,
    jobVacanciesRemaining: 3,
    jobApplicants: ["JOBSN202308060002", "JOBSN202308060007"],
  },
];

export const candidates = [
  {
    id: "JOBSN202308060001",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    currentJobLocation: "Bangalore",
    preferredJobLocation: ["Mumbai", "Pune"],
    currentSalary: 12, // in LPA
    noticePeriod: 60, // in days
    skills: ["JavaScript", "React", "Node.js"],
    currentCompany: "Infosys",
    previousCompanies: ["TCS", "Wipro"],
    totalExperience: 5, // in years
    collegeName: "IIT Bombay",
    collegeLocation: "Mumbai",
    graduationYear: 2018,
    linkedinProfile: "https://www.linkedin.com/in/johndoe",
    githubProfile: "https://github.com/johndoe",
    resume: "resume_johndoe.pdf",
    applications: [
      { jobId: "49790139", status: "Applied" },
      { jobId: "49790140", status: "Interviewed" },
    ],
    dateOfBirth: "1990-05-15", // in YYYY-MM-DD format
    location: "Bangalore",
    contactNumber: "+91-9876543210",
  },
  {
    id: "JOBSN202308060002",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    currentJobLocation: "Delhi",
    preferredJobLocation: ["Delhi", "Gurgaon"],
    currentSalary: 10, // in LPA
    noticePeriod: 30, // in days
    skills: ["Python", "Django", "Machine Learning"],
    currentCompany: "HCL",
    previousCompanies: ["Tech Mahindra", "Cognizant"],
    totalExperience: 4, // in years
    collegeName: "NIT Delhi",
    collegeLocation: "Delhi",
    graduationYear: 2019,
    linkedinProfile: "https://www.linkedin.com/in/janesmith",
    githubProfile: "https://github.com/janesmith",
    resume: "resume_janesmith.pdf",
    applications: [
      { jobId: "49790141", status: "Shortlisted" },
      { jobId: "49790142", status: "Rejected" },
    ],
    dateOfBirth: "1992-08-22", // in YYYY-MM-DD format
    location: "Delhi",
    contactNumber: "+91-9123456789",
  },
  {
    id: "JOBSN202308060003",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    currentJobLocation: "Hyderabad",
    preferredJobLocation: ["Hyderabad", "Chennai"],
    currentSalary: 14, // in LPA
    noticePeriod: 45, // in days
    skills: ["Java", "Spring Boot", "Microservices"],
    currentCompany: "Accenture",
    previousCompanies: ["Capgemini", "Oracle"],
    totalExperience: 6, // in years
    collegeName: "IIT Hyderabad",
    collegeLocation: "Hyderabad",
    graduationYear: 2017,
    linkedinProfile: "https://www.linkedin.com/in/alicejohnson",
    githubProfile: "https://github.com/alicejohnson",
    resume: "resume_alicejohnson.pdf",
    applications: [
      { jobId: "49790143", status: "Applied" },
      { jobId: "49790144", status: "Offer Extended" },
    ],
    dateOfBirth: "1989-11-05", // in YYYY-MM-DD format
    location: "Hyderabad",
    contactNumber: "+91-9234567890",
  },
  {
    id: "JOBSN202308060004",
    firstName: "Robert",
    lastName: "Williams",
    email: "robert.williams@example.com",
    currentJobLocation: "Pune",
    preferredJobLocation: ["Pune", "Mumbai"],
    currentSalary: 11, // in LPA
    noticePeriod: 90, // in days
    skills: ["C#", ".NET Core", "Azure"],
    currentCompany: "Microsoft",
    previousCompanies: ["IBM", "SAP"],
    totalExperience: 7, // in years
    collegeName: "BITS Pilani",
    collegeLocation: "Pilani",
    graduationYear: 2016,
    linkedinProfile: "https://www.linkedin.com/in/robertwilliams",
    githubProfile: "https://github.com/robertwilliams",
    resume: "resume_robertwilliams.pdf",
    applications: [
      { jobId: "49790145", status: "Applied" },
      { jobId: "49790146", status: "Interviewed" },
    ],
    dateOfBirth: "1987-03-30", // in YYYY-MM-DD format
    location: "Pune",
    contactNumber: "+91-9345678901",
  },
  {
    id: "JOBSN202308060005",
    firstName: "Emily",
    lastName: "Brown",
    email: "emily.brown@example.com",
    currentJobLocation: "Chennai",
    preferredJobLocation: ["Chennai", "Bangalore"],
    currentSalary: 9, // in LPA
    noticePeriod: 30, // in days
    skills: ["PHP", "Laravel", "MySQL"],
    currentCompany: "Zoho",
    previousCompanies: ["Freshworks", "Mindtree"],
    totalExperience: 3, // in years
    collegeName: "Anna University",
    collegeLocation: "Chennai",
    graduationYear: 2020,
    linkedinProfile: "https://www.linkedin.com/in/emilybrown",
    githubProfile: "https://github.com/emilybrown",
    resume: "resume_emilybrown.pdf",
    applications: [
      { jobId: "49790147", status: "Applied" },
      { jobId: "49790148", status: "Shortlisted" },
    ],
    dateOfBirth: "1995-07-19", // in YYYY-MM-DD format
    location: "Chennai",
    contactNumber: "+91-9456789012",
  },
  {
    id: "JOBSN202308060006",
    firstName: "Michael",
    lastName: "Taylor",
    email: "michael.taylor@example.com",
    currentJobLocation: "Mumbai",
    preferredJobLocation: ["Mumbai", "Bangalore"],
    currentSalary: 13, // in LPA
    noticePeriod: 60, // in days
    skills: ["Angular", "TypeScript", "Node.js"],
    currentCompany: "TCS",
    previousCompanies: ["Cognizant", "Infosys"],
    totalExperience: 5, // in years
    collegeName: "IIT Bombay",
    collegeLocation: "Mumbai",
    graduationYear: 2018,
    linkedinProfile: "https://www.linkedin.com/in/michaeltaylor",
    githubProfile: "https://github.com/michaeltaylor",
    resume: "resume_michaeltaylor.pdf",
    applications: [
      { jobId: "49790149", status: "Applied" },
      { jobId: "49790150", status: "Offer Extended" },
    ],
    dateOfBirth: "1991-04-28", // in YYYY-MM-DD format
    location: "Mumbai",
    contactNumber: "+91-9567890123",
  },
  {
    id: "JOBSN202308060007",
    firstName: "Jessica",
    lastName: "Davis",
    email: "jessica.davis@example.com",
    currentJobLocation: "Kolkata",
    preferredJobLocation: ["Kolkata", "Delhi"],
    currentSalary: 8, // in LPA
    noticePeriod: 45, // in days
    skills: ["Ruby on Rails", "PostgreSQL", "Redis"],
    currentCompany: "Tech Mahindra",
    previousCompanies: ["Wipro", "HCL"],
    totalExperience: 4, // in years
    collegeName: "Jadavpur University",
    collegeLocation: "Kolkata",
    graduationYear: 2019,
    linkedinProfile: "https://www.linkedin.com/in/jessicadavis",
    githubProfile: "https://github.com/jessicadavis",
    resume: "resume_jessicadavis.pdf",
    applications: [
      { jobId: "49790151", status: "Applied" },
      { jobId: "49790152", status: "Rejected" },
    ],
    dateOfBirth: "1992-09-14", // in YYYY-MM-DD format
    location: "Kolkata",
    contactNumber: "+91-9678901234",
  },
  {
    id: "JOBSN202308060008",
    firstName: "Daniel",
    lastName: "Moore",
    email: "daniel.moore@example.com",
    currentJobLocation: "Ahmedabad",
    preferredJobLocation: ["Ahmedabad", "Surat"],
    currentSalary: 7, // in LPA
    noticePeriod: 60, // in days
    skills: ["Go", "Kubernetes", "Docker"],
    currentCompany: "Zomato",
    previousCompanies: ["Swiggy", "Paytm"],
    totalExperience: 3, // in years
    collegeName: "IIT Gandhinagar",
    collegeLocation: "Gandhinagar",
    graduationYear: 2020,
    linkedinProfile: "https://www.linkedin.com/in/danielmoore",
    githubProfile: "https://github.com/danielmoore",
    resume: "resume_danielmoore.pdf",
    applications: [
      { jobId: "49790153", status: "Applied" },
      { jobId: "49790154", status: "Shortlisted" },
    ],
    dateOfBirth: "1996-06-25", // in YYYY-MM-DD format
    location: "Ahmedabad",
    contactNumber: "+91-9801234567",
  },
];

export const consultants = [
  {
    id: "JOBSNV0001",
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    phone: "+91-9876543211",
    addressStreet: "123 Main St",
    addressCity: "Mumbai",
    addressDistrict: "Mumbai Suburban",
    addressState: "Maharashtra",
    addressCountry: "India",
    position: "Senior Consultant",
    salary: "15 LPA",
    dateOfBirth: "1985-04-22",
    profilePic: "profilepic_alice.jpg",
    startDate: "2020-01-15",
    endDate: null,
    workingLocation: "Mumbai",
    currentPotentialPoints: 120.5,
    cumulativePotentialPoints: 450.75,
    createdAt: "2020-01-01T10:00:00Z",
    updatedAt: "2024-08-01T10:00:00Z",
  },
  {
    id: "JOBSNV0002",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    phone: "+91-9876543212",
    addressStreet: "456 Elm St",
    addressCity: "Delhi",
    addressDistrict: "New Delhi",
    addressState: "Delhi",
    addressCountry: "India",
    position: "Junior Consultant",
    salary: "8 LPA",
    dateOfBirth: "1992-07-10",
    profilePic: "profilepic_bob.jpg",
    startDate: "2021-03-20",
    endDate: null,
    workingLocation: "Delhi",
    currentPotentialPoints: 80.0,
    cumulativePotentialPoints: 300.0,
    createdAt: "2021-03-01T09:00:00Z",
    updatedAt: "2024-08-01T09:00:00Z",
  },
  {
    id: "JOBSNV0003",
    firstName: "Carol",
    lastName: "Williams",
    email: "carol.williams@example.com",
    phone: "+91-9876543213",
    addressStreet: "789 Pine St",
    addressCity: "Chennai",
    addressDistrict: "Chennai",
    addressState: "Tamil Nadu",
    addressCountry: "India",
    position: "Consultant",
    salary: "10 LPA",
    dateOfBirth: "1988-02-15",
    profilePic: "profilepic_carol.jpg",
    startDate: "2019-05-10",
    endDate: null,
    workingLocation: "Chennai",
    currentPotentialPoints: 95.0,
    cumulativePotentialPoints: 400.0,
    createdAt: "2019-05-01T08:00:00Z",
    updatedAt: "2024-08-01T08:00:00Z",
  },
  {
    id: "JOBSNV0004",
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    phone: "+91-9876543214",
    addressStreet: "101 Maple St",
    addressCity: "Kolkata",
    addressDistrict: "Kolkata",
    addressState: "West Bengal",
    addressCountry: "India",
    position: "Lead Consultant",
    salary: "18 LPA",
    dateOfBirth: "1983-11-20",
    profilePic: "profilepic_david.jpg",
    startDate: "2018-07-01",
    endDate: null,
    workingLocation: "Kolkata",
    currentPotentialPoints: 150.0,
    cumulativePotentialPoints: 600.0,
    createdAt: "2018-07-01T07:00:00Z",
    updatedAt: "2024-08-01T07:00:00Z",
  },
  {
    id: "JOBSNV0005",
    firstName: "Eve",
    lastName: "Davis",
    email: "eve.davis@example.com",
    phone: "+91-9876543215",
    addressStreet: "202 Birch St",
    addressCity: "Hyderabad",
    addressDistrict: "Hyderabad",
    addressState: "Telangana",
    addressCountry: "India",
    position: "Consultant",
    salary: "12 LPA",
    dateOfBirth: "1990-09-10",
    profilePic: "profilepic_eve.jpg",
    startDate: "2020-09-01",
    endDate: null,
    workingLocation: "Hyderabad",
    currentPotentialPoints: 110.0,
    cumulativePotentialPoints: 450.0,
    createdAt: "2020-09-01T06:00:00Z",
    updatedAt: "2024-08-01T06:00:00Z",
  },
  {
    id: "JOBSNV0006",
    firstName: "Frank",
    lastName: "Miller",
    email: "frank.miller@example.com",
    phone: "+91-9876543216",
    addressStreet: "303 Cedar St",
    addressCity: "Bangalore",
    addressDistrict: "Bangalore Urban",
    addressState: "Karnataka",
    addressCountry: "India",
    position: "Senior Consultant",
    salary: "14 LPA",
    dateOfBirth: "1987-03-05",
    profilePic: "profilepic_frank.jpg",
    startDate: "2017-04-10",
    endDate: null,
    workingLocation: "Bangalore",
    currentPotentialPoints: 130.0,
    cumulativePotentialPoints: 500.0,
    createdAt: "2017-04-01T05:00:00Z",
    updatedAt: "2024-08-01T05:00:00Z",
  },
  {
    id: "JOBSNV0007",
    firstName: "Grace",
    lastName: "Wilson",
    email: "grace.wilson@example.com",
    phone: "+91-9876543217",
    addressStreet: "404 Spruce St",
    addressCity: "Ahmedabad",
    addressDistrict: "Ahmedabad",
    addressState: "Gujarat",
    addressCountry: "India",
    position: "Consultant",
    salary: "11 LPA",
    dateOfBirth: "1989-06-18",
    profilePic: "profilepic_grace.jpg",
    startDate: "2021-02-15",
    endDate: null,
    workingLocation: "Ahmedabad",
    currentPotentialPoints: 100.0,
    cumulativePotentialPoints: 410.0,
    createdAt: "2021-02-01T04:00:00Z",
    updatedAt: "2024-08-01T04:00:00Z",
  },
  {
    id: "JOBSNV0008",
    firstName: "Hank",
    lastName: "Moore",
    email: "hank.moore@example.com",
    phone: "+91-9876543218",
    addressStreet: "505 Pineapple St",
    addressCity: "Pune",
    addressDistrict: "Pune",
    addressState: "Maharashtra",
    addressCountry: "India",
    position: "Junior Consultant",
    salary: "9 LPA",
    dateOfBirth: "1993-12-14",
    profilePic: "profilepic_hank.jpg",
    startDate: "2022-01-20",
    endDate: null,
    workingLocation: "Pune",
    currentPotentialPoints: 70.0,
    cumulativePotentialPoints: 280.0,
    createdAt: "2022-01-01T03:00:00Z",
    updatedAt: "2024-08-01T03:00:00Z",
  },
  {
    id: "JOBSNV0009",
    firstName: "Ivy",
    lastName: "Taylor",
    email: "ivy.taylor@example.com",
    phone: "+91-9876543219",
    addressStreet: "606 Oak St",
    addressCity: "Gurgaon",
    addressDistrict: "Gurgaon",
    addressState: "Haryana",
    addressCountry: "India",
    position: "Consultant",
    salary: "13 LPA",
    dateOfBirth: "1991-11-05",
    profilePic: "profilepic_ivy.jpg",
    startDate: "2019-10-15",
    endDate: null,
    workingLocation: "Gurgaon",
    currentPotentialPoints: 105.0,
    cumulativePotentialPoints: 420.0,
    createdAt: "2019-10-01T02:00:00Z",
    updatedAt: "2024-08-01T02:00:00Z",
  },
  {
    id: "JOBSNV0010",
    firstName: "Jack",
    lastName: "Anderson",
    email: "jack.anderson@example.com",
    phone: "+91-9876543220",
    addressStreet: "707 Palm St",
    addressCity: "Noida",
    addressDistrict: "Gautam Buddha Nagar",
    addressState: "Uttar Pradesh",
    addressCountry: "India",
    position: "Lead Consultant",
    salary: "17 LPA",
    dateOfBirth: "1986-08-25",
    profilePic: "profilepic_jack.jpg",
    startDate: "2018-12-01",
    endDate: null,
    workingLocation: "Noida",
    currentPotentialPoints: 140.0,
    cumulativePotentialPoints: 550.0,
    createdAt: "2018-12-01T01:00:00Z",
    updatedAt: "2024-08-01T01:00:00Z",
  },
];

export const companies = [
  // Banking Sector
  {
    companyId: "00001",
    companyName: "State Bank of India",
    companyLogo: "https://example.com/logos/sbi_logo.png",
    companySector: "Banking",
    companyDescription:
      "State Bank of India (SBI) is a multinational, public sector banking and financial services statutory body headquartered in Mumbai, India.",
  },
  {
    companyId: "00002",
    companyName: "HDFC Bank",
    companyLogo: "https://example.com/logos/hdfc_logo.png",
    companySector: "Banking",
    companyDescription:
      "HDFC Bank Limited is an Indian banking and financial services company headquartered in Mumbai.",
  },
  {
    companyId: "00003",
    companyName: "ICICI Bank",
    companyLogo: "https://example.com/logos/icici_logo.png",
    companySector: "Banking",
    companyDescription:
      "ICICI Bank Limited is an Indian multinational banking and financial services company headquartered in Vadodara.",
  },
  {
    companyId: "00004",
    companyName: "Axis Bank",
    companyLogo: "https://example.com/logos/axis_logo.png",
    companySector: "Banking",
    companyDescription:
      "Axis Bank is an Indian banking and financial services company headquartered in Mumbai, Maharashtra.",
  },
  {
    companyId: "00005",
    companyName: "Punjab National Bank",
    companyLogo: "https://example.com/logos/pnb_logo.png",
    companySector: "Banking",
    companyDescription:
      "Punjab National Bank (PNB) is an Indian public sector bank headquartered in New Delhi, India.",
  },

  // Technology Sector
  {
    companyId: "00006",
    companyName: "Infosys",
    companyLogo: "https://example.com/logos/infosys_logo.png",
    companySector: "Technology",
    companyDescription:
      "Infosys Limited is an Indian multinational corporation that provides business consulting, information technology, and outsourcing services.",
  },
  {
    companyId: "00007",
    companyName: "Tata Consultancy Services",
    companyLogo: "https://example.com/logos/tcs_logo.png",
    companySector: "Technology",
    companyDescription:
      "Tata Consultancy Services (TCS) is an Indian multinational information technology services and consulting company headquartered in Mumbai, Maharashtra.",
  },
  {
    companyId: "00008",
    companyName: "Wipro",
    companyLogo: "https://example.com/logos/wipro_logo.png",
    companySector: "Technology",
    companyDescription:
      "Wipro Limited is an Indian multinational corporation that provides information technology, consulting, and business process services.",
  },

  // Healthcare Sector
  {
    companyId: "00009",
    companyName: "Apollo Hospitals",
    companyLogo: "https://example.com/logos/apollo_logo.png",
    companySector: "Healthcare",
    companyDescription:
      "Apollo Hospitals Enterprise Limited is an Indian multinational hospital chain headquartered in Chennai, India.",
  },
  {
    companyId: "00010",
    companyName: "Fortis Healthcare",
    companyLogo: "https://example.com/logos/fortis_logo.png",
    companySector: "Healthcare",
    companyDescription:
      "Fortis Healthcare Limited is a leading integrated healthcare delivery service provider in India.",
  },

  // Finance Sector
  {
    companyId: "00011",
    companyName: "Bajaj Finance",
    companyLogo: "https://example.com/logos/bajaj_finance_logo.png",
    companySector: "Finance",
    companyDescription:
      "Bajaj Finance Limited is an Indian non-banking financial company headquartered in Pune, India.",
  },
  {
    companyId: "00012",
    companyName: "HDFC Asset Management",
    companyLogo: "https://example.com/logos/hdfc_amc_logo.png",
    companySector: "Finance",
    companyDescription:
      "HDFC Asset Management Company Limited (HDFC AMC) is one of the largest mutual fund managers in India.",
  },

  // Education Sector
  {
    companyId: "00013",
    companyName: "Byju's",
    companyLogo: "https://example.com/logos/byjus_logo.png",
    companySector: "Education",
    companyDescription:
      "Byju's is an Indian multinational educational technology company headquartered in Bengaluru, India.",
  },
  {
    companyId: "00014",
    companyName: "Unacademy",
    companyLogo: "https://example.com/logos/unacademy_logo.png",
    companySector: "Education",
    companyDescription:
      "Unacademy is an Indian online education technology company based in Bengaluru, India.",
  },
];

export const sectors = [
  {
    sectorId: 0,
    sectorName: "Banking",
    domains: [
      {
        domainId: 0,
        domainName: "Retail Banking",
        levels: [
          { levelId: 0, levelName: "Entry Level" },
          { levelId: 1, levelName: "Mid Level" },
          { levelId: 2, levelName: "Senior Level" },
        ],
      },
      {
        domainId: 1,
        domainName: "Corporate Banking",
        levels: [
          { levelId: 0, levelName: "Entry Level" },
          { levelId: 1, levelName: "Mid Level" },
          { levelId: 2, levelName: "Senior Level" },
        ],
      },
      {
        domainId: 2,
        domainName: "Investment Banking",
        levels: [
          { levelId: 0, levelName: "Entry Level" },
          { levelId: 1, levelName: "Mid Level" },
          { levelId: 2, levelName: "Senior Level" },
        ],
      },
    ],
  },
  {
    sectorId: 1,
    sectorName: "Information Technology",
    domains: [
      {
        domainId: 0,
        domainName: "Software Development",
        levels: [
          { levelId: 0, levelName: "Junior Developer" },
          { levelId: 1, levelName: "Mid Level Developer" },
          { levelId: 2, levelName: "Senior Developer" },
        ],
      },
      {
        domainId: 1,
        domainName: "Cybersecurity",
        levels: [
          { levelId: 0, levelName: "Analyst" },
          { levelId: 1, levelName: "Specialist" },
          { levelId: 2, levelName: "Manager" },
        ],
      },
      {
        domainId: 2,
        domainName: "Data Science",
        levels: [
          { levelId: 0, levelName: "Data Analyst" },
          { levelId: 1, levelName: "Data Scientist" },
          { levelId: 2, levelName: "Data Engineer" },
        ],
      },
    ],
  },
  {
    sectorId: 2,
    sectorName: "Healthcare",
    domains: [
      {
        domainId: 0,
        domainName: "Pharmaceuticals",
        levels: [
          { levelId: 0, levelName: "Research Assistant" },
          { levelId: 1, levelName: "Research Scientist" },
          { levelId: 2, levelName: "Lab Manager" },
        ],
      },
      {
        domainId: 1,
        domainName: "Medical Devices",
        levels: [
          { levelId: 0, levelName: "Technician" },
          { levelId: 1, levelName: "Engineer" },
          { levelId: 2, levelName: "Senior Engineer" },
        ],
      },
      {
        domainId: 2,
        domainName: "Healthcare Services",
        levels: [
          { levelId: 0, levelName: "Assistant" },
          { levelId: 1, levelName: "Practitioner" },
          { levelId: 2, levelName: "Senior Practitioner" },
        ],
      },
    ],
  },
  // Add more sectors, domains, and levels as needed
];
